version: '3.8'
services:
  back:
    container_name: back_shark
    hostname: back_shark
    build:
      context: ./back
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - ./back:/go/src
    ports:
      - "3000:3000"